"""Added profile info

Revision ID: 408108c4d166
Revises: 158a9eb10134
Create Date: 2024-07-18 14:57:33.539139

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "408108c4d166"
down_revision: Union[str, None] = "158a9eb10134"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("about", sa.String(length=1024), nullable=False))
    op.add_column("users", sa.Column("social_links", postgresql.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "social_links")
    op.drop_column("users", "about")
    # ### end Alembic commands ###
