"""Added

Revision ID: 3187f544645d
Revises: 408108c4d166
Create Date: 2024-08-04 11:07:46.547564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3187f544645d"
down_revision: Union[str, None] = "408108c4d166"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_subscriptions",
        sa.Column("subscriber_id", sa.UUID(), nullable=False),
        sa.Column("subscribed_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["subscribed_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["subscriber_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subscriber_id", "subscribed_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_subscriptions")
    # ### end Alembic commands ###
