version: '3.9'

services:
  server:
    container_name: server
    restart: on-failure
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/:/project/
    env_file:
      - ./server/.docker-env

  db:
    container_name: db
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./.postgres-env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    restart: on-failure
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    command: bash -c "npm run dev"
    ports:
      - 5000:5000
    env_file:
      - ./frontend/video-hosting/.docker-env
    volumes:
      - ./frontend/video-hosting/:/project/
      - node_modules:/project/node_modules
    depends_on:
      - server

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    env_file:
      - ./.postgres-env
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules: