"""Update users table

Revision ID: b189840f6b74
Revises: ccd513b92836
Create Date: 2024-12-18 15:28:48.262227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.users.models import UserModel


# revision identifiers, used by Alembic.
revision: str = "b189840f6b74"
down_revision: Union[str, None] = "ccd513b92836"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_verified_email", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("telegram_username", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_verified_telegram", sa.Boolean(), nullable=True))

    query = (
        sa.update(UserModel)
        .values(
            is_verified_email=False,
            is_verified_telegram=False,
        )
    )
    op.execute(query)

    op.alter_column("users", "is_verified_email", nullable=False)
    op.alter_column("users", "is_verified_telegram", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified_telegram")
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "is_verified_email")
    # ### end Alembic commands ###
