"""Add 'expires_at' column to 'sessions' table

Revision ID: 5565c8b7123d
Revises: 37e4f665cb72
Create Date: 2024-12-13 23:15:51.925232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5565c8b7123d'
down_revision: Union[str, None] = '37e4f665cb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'expires_at')
    # ### end Alembic commands ###
