"""Add 'liked_at' to 'user_video_likes' table

Revision ID: 1c55338d965d
Revises: cea7fd972d27
Create Date: 2024-12-05 13:59:26.951515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c55338d965d'
down_revision: Union[str, None] = 'cea7fd972d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_video_likes', sa.Column('liked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_video_likes', 'liked_at')
    # ### end Alembic commands ###
