"""Add 'watched_at' column to watch history

Revision ID: cea7fd972d27
Revises: 95b8d36df433
Create Date: 2024-12-04 12:57:08.604415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea7fd972d27'
down_revision: Union[str, None] = '95b8d36df433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_video_history', sa.Column('watched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_video_history', 'watched_at')
    # ### end Alembic commands ###
