"""Update telegram columns

Revision ID: 1dcdd0688f4e
Revises: b189840f6b74
Create Date: 2024-12-22 14:26:34.436340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcdd0688f4e'
down_revision: Union[str, None] = 'b189840f6b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('playlists_description_trgm_idx', table_name='playlists', postgresql_using='gin')
    op.drop_index('playlists_title_trgm_idx', table_name='playlists', postgresql_using='gin')
    op.add_column('users', sa.Column('telegram_chat_id', sa.Integer(), nullable=True))
    op.drop_index('users_about_trgm_idx', table_name='users', postgresql_using='gin')
    op.drop_index('users_username_trgm_idx', table_name='users', postgresql_using='gin')
    op.create_unique_constraint(None, 'users', ['telegram_username'])
    op.create_unique_constraint(None, 'users', ['telegram_chat_id'])
    op.drop_index('videos_description_trgm_idx', table_name='videos', postgresql_using='gin')
    op.drop_index('videos_title_trgm_idx', table_name='videos', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('videos_title_trgm_idx', 'videos', ['title'], unique=False, postgresql_using='gin')
    op.create_index('videos_description_trgm_idx', 'videos', ['description'], unique=False, postgresql_using='gin')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('users_username_trgm_idx', 'users', ['username'], unique=False, postgresql_using='gin')
    op.create_index('users_about_trgm_idx', 'users', ['about'], unique=False, postgresql_using='gin')
    op.drop_column('users', 'telegram_chat_id')
    op.create_index('playlists_title_trgm_idx', 'playlists', ['title'], unique=False, postgresql_using='gin')
    op.create_index('playlists_description_trgm_idx', 'playlists', ['description'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
