"""Made

Revision ID: e690f581c89f
Revises: 50a100256c20
Create Date: 2024-10-15 22:00:41.441456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e690f581c89f"
down_revision: Union[str, None] = "50a100256c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("playlists_title_key", "playlists", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("playlists_title_key", "playlists", ["title"])
    # ### end Alembic commands ###
