"""Added 'private' column

Revision ID: 50a100256c20
Revises: 0cadc7195a5b
Create Date: 2024-08-14 20:32:39.562429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a100256c20'
down_revision: Union[str, None] = '0cadc7195a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'private')
    # ### end Alembic commands ###
