"""Added 'user_id' column

Revision ID: 5e003d1c4783
Revises: 1804f91ca12f
Create Date: 2024-07-14 00:13:16.259122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e003d1c4783'
down_revision: Union[str, None] = '1804f91ca12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###
